algoritmo "Exercício vetor lista inversa"
// Função : Escrever um algoritmo que leia a as inicias do nome do usuário  e depois exiba duas listas, uma com os nomes  digitadas e outra com os nomes digitadas na ordem inversa
// Autor : Júlio César Oliveira Siriano
// Data : 28/02/2025
var

   letrasDigitada : vetor [1..6] de caractere
   contador : inteiro

inicio

      Para contador de 1 ate 6 Faca
      
           Escreval("Digite as inicias: ")
           leia(LetrasDigitada[ contador ] )
      
      FimPara
      
      Escreval
      Escreval("As inicias digitadas foram: ")
      
      para contador de 1 ate 6 Faca
      
            Escreval(LetrasDigitada[ contador ] )

      
      FimPara
      
      Escreval
      Escreval("As inicias digitadas em ordem inversa foram: ")

      para contador de 6 ate 1 passo -1 Faca

            Escreval(LetrasDigitada[ contador ] )


      FimPara


fimalgoritmo
