algoritmo "Exercício Lan House"
// Função : Programa desenvolvido para saber quantos minutos o cliente permaneceu na lan-house
// Autor : Júlio César Oliveira Siriano
// Data : 12/01/2022
var

   minutos, totalAPagar : real


inicio

      Escreval("Digite a quantidade em minutos utilizada pelo cliente: ")
      leia(minutos)

      totalAPagar <- minutos * ((1/60)*2)

      Escreval("Total a pagar: ", totalAPagar, " reais.")

fimalgoritmo

