algoritmo "Exercício enquanto faça número 1 a 10"
// Função :   Um algoritmo que só aceite um número de 1 a 10
// Autor : Júlio César Oliveira Siriano
// Data : 26/02/2025
var

    numero : inteiro

inicio

       Escreval("Digite um número: ")
       leia(numero)
       
       Enquanto ( numero < 0  ) ou ( numero > 10 ) faca
       
                 Escreval("Atenção! Você precisa digitar um número entre 0 e 10.")
                 Escreval
                 Escreval
                 Escreval("Digite novamente um número no intervalo de 0 a 10")
                 
                 leia(numero)
       
       FimEnquanto
       Escreval
       Escreval
       Escreval("Muito bem! O número ", numero, " está no intervalo de 0 a 10.")


fimalgoritmo
