algoritmo "Exercício ENquanto faça fatorial"
// Função :  Um algoritmo que leia um número e seu fatorial
// Autor :  Júlio Céasar Oliveira Siriano
// Data : 26/02/2025
var

      numero, contador : inteiro
      fatorial : real


inicio

       Escreval("Digite um número: ")
       leia(numero)
       
       contador <- 1
       
       fatorial <- numero
       
       Enquanto ( contador < numero ) faca

                fatorial <- fatorial * contador
                
                contador<- contador + 1
       
       FimEnquanto
       
       Escreval ("O fatorial de ", numero, " é ", fatorial, "." )


fimalgoritmo
